"""One definition of what generated code is (#432).

`cgis orphans` is correct about generated code — nothing constructs a betterproto
stub, and nobody deletes one either — so every such class dilutes a report whose
whole value is that a reader acts on it. Measured on `Ownima/owner-api` at
`b7d02fe6`, five of the six reported orphans were betterproto entities and the
sixth was a nested pydantic `Config`: the report had no actionable row left.

The decision lives in one function so "what is generated" has one answer, the
same way `is_test_path` owns "what is a test". `Node.is_generated` is its cached
result, stamped once per file by the pipeline, so a query filters in SQL without
re-reading source.

Two things must both be true, and each carries its own weight:

* a **self-declaration** — `@generated`, "Generated by X", "auto-generated". Not
  the bare stem `generat`: a code-generation project's own template says
  "template for the generated client" and is not itself generated, and matching
  the stem hid every class in such a file. `@generated` needs no companion; it is
  a machine token nobody writes in prose.
* for the English instruction, a **"do not edit"** beside that declaration. On
  its own it is ordinary prose.

Only the file's head is read, since a marker further down is commentary rather
than a claim about the file. The window is fifteen lines: openapi-generator and
swagger-codegen put both markers inside the module docstring, at roughly lines
ten and twelve, and a five-line window silently missed every one of their files.
Widening it costs nothing measurable — across owner-api the fifteen-line window
classifies exactly the six files the five-line one did, with no new candidates.

**Known limit**: a file that embeds a real generated header in its own first
fifteen lines — a fixture, or a generator's golden output committed as data — is
indistinguishable from generated source by header inspection, and is classified
as such. `--include-generated` is the way back.
"""

import re

# Scanned window. Fifteen lines reaches openapi-generator's docstring markers
# (~lines 10 and 12) with headroom; protoc and betterproto declare on line 1.
_HEADER_LINES = 15

# A character cap on top of the line count, so this check's cost does not depend
# on the file: a minified or single-line source has no newline to stop `split`
# at, and the regexes would then scan the whole thing. Measured rather than
# picked — the largest fifteen-line window across owner-api's six generated files
# is under 1 KB, so this carries several times the headroom it needs.
_HEADER_CHARS = 4096

# `@generated` is a machine token and the lowercase spelling is the convention,
# so it is matched exactly and stands alone. (Java's `@Generated` annotation is a
# real spelling, but it sits on a declaration rather than a header line, and no
# Java extractor exists yet — one can add it with a test rather than inherit it.)
_GENERATED = re.compile(r"@generated")

# A file saying who made it: "Generated by the protocol buffer compiler",
# "Generated by OpenAPI Generator", "Auto-generated version info". A description
# of generated things — "the generated client", "generated by the client and
# repeated on retry" — is not a self-declaration and must not match.
_DECLARATION = re.compile(r"generated by|auto[- ]?generated|generated with", re.IGNORECASE)

# Ordinary English, so it is evidence only beside a declaration: protoc shouts
# it on the same line, openapi-generator writes it two lines below.
_DO_NOT_EDIT = re.compile(r"do not edit", re.IGNORECASE)


def is_generated_source(code: str) -> bool:
    """Does this source declare itself machine-generated in its header?

    Used to keep generated classes out of `cgis orphans` by default: they are
    genuinely unreferenced, and reporting them is noise rather than a finding.
    `--include-generated` puts them back for the rare audit that wants them.
    """
    header = code[:_HEADER_CHARS].split("\n", maxsplit=_HEADER_LINES)[:_HEADER_LINES]
    if any(_GENERATED.search(line) for line in header):
        return True
    return any(_DO_NOT_EDIT.search(line) for line in header) and any(
        _DECLARATION.search(line) for line in header
    )
