"""The names a JavaScript runtime provides without an import (#111).

Plain data in `core` because two layers read it: the TypeScript extractor, to
record which of these names a file rebinds, and the resolver, to rewrite calls
on the ones it does not.
"""

#: ECMAScript standard globals plus the browser and Node host objects a UI or
#: server codebase calls directly. A receiver is matched by its root segment only,
#: so `Math.max` and `document.body.append` both qualify; `arr.map` does not.
JS_GLOBALS: frozenset[str] = frozenset(
    {
        # ECMAScript value/function globals
        "globalThis",
        "isFinite",
        "isNaN",
        "parseFloat",
        "parseInt",
        "encodeURI",
        "encodeURIComponent",
        "decodeURI",
        "decodeURIComponent",
        "structuredClone",
        "queueMicrotask",
        # ECMAScript constructors and namespaces
        "Array",
        "ArrayBuffer",
        "Atomics",
        "BigInt",
        "Boolean",
        "DataView",
        "Date",
        "Error",
        "EvalError",
        "Float32Array",
        "Float64Array",
        "Function",
        "Int8Array",
        "Int16Array",
        "Int32Array",
        "Intl",
        "JSON",
        "Map",
        "Math",
        "Number",
        "Object",
        "Promise",
        "Proxy",
        "RangeError",
        "ReferenceError",
        "Reflect",
        "RegExp",
        "Set",
        "String",
        "Symbol",
        "SyntaxError",
        "TypeError",
        "Uint8Array",
        "Uint8ClampedArray",
        "Uint16Array",
        "Uint32Array",
        "URIError",
        "WeakMap",
        "WeakRef",
        "WeakSet",
        # Host globals shared by browsers and Node
        "console",
        "setTimeout",
        "clearTimeout",
        "setInterval",
        "clearInterval",
        "fetch",
        "URL",
        "URLSearchParams",
        "AbortController",
        "TextEncoder",
        "TextDecoder",
        "Blob",
        "FormData",
        "Headers",
        "Request",
        "Response",
        "crypto",
        "performance",
        # Browser globals
        "window",
        "document",
        "navigator",
        "location",
        "history",
        "localStorage",
        "sessionStorage",
        "requestAnimationFrame",
        "cancelAnimationFrame",
        "getComputedStyle",
        "matchMedia",
        "alert",
        "confirm",
        "prompt",
        "ResizeObserver",
        "IntersectionObserver",
        "MutationObserver",
        "CustomEvent",
        "Event",
        "WebSocket",
        "Worker",
        "Image",
        # Node globals
        "global",
        "process",
        "Buffer",
        "require",
        "setImmediate",
        "clearImmediate",
    }
)
