"""Inject a Mermaid diagram into README.md between CGIS graph comment anchors.

Reads docs/architecture/diagrams/pipeline_flow.mermaid and replaces the
content between <!-- START_CGIS_GRAPH --> and <!-- END_CGIS_GRAPH --> in
README.md. Idempotent — running multiple times produces identical output.

Optional --db argument enables a node reference table with GitHub source links.
"""

import argparse
import subprocess
from pathlib import Path

from cgis.core.models import NodeNamespace
from cgis.query.engine import BEHAVIORAL_EDGE_TYPES, QueryEngine
from cgis.storage.sqlite_store import SQLiteStore

_README = Path("README.md")
_DIAGRAM = Path("docs/architecture/diagrams/pipeline_flow.mermaid")
_START = "<!-- START_CGIS_GRAPH -->"
_END = "<!-- END_CGIS_GRAPH -->"
_SELF_DOC_NOTE = (
    "> *Auto-generated by CGIS parsing its own source — "
    "the tool documents itself.*\n"
)


def _repo_url() -> str:
    try:
        raw = subprocess.check_output(
            ["git", "remote", "get-url", "origin"], text=True
        ).strip()
        if raw.startswith("git@github.com:"):
            raw = raw.replace("git@github.com:", "https://github.com/")
        return raw.removesuffix(".git")
    except subprocess.CalledProcessError:
        return ""


def _node_table(
    db: str, fqn: str, depth: int, repo_url: str, path_prefix: str
) -> str:
    with SQLiteStore(db) as store:
        nodes, _ = QueryEngine(store).get_flow_graph(
            fqn,
            max_depth=depth,
            allowed_edge_types=BEHAVIORAL_EDGE_TYPES,
            show_external=False,
        )
    internal = sorted(
        [n for n in nodes if n.namespace == NodeNamespace.INTERNAL],
        key=lambda n: (n.file_path, n.start_line),
    )
    rows = [
        "| Symbol | Type | File |",
        "|--------|------|------|",
    ]
    for node in internal:
        rel_path = node.file_path.replace("\\", "/")
        filename = rel_path.split("/")[-1]
        full_path = f"{path_prefix}{rel_path}" if path_prefix else rel_path
        if repo_url:
            link = f"{repo_url}/blob/main/{full_path}#L{node.start_line}"
            file_cell = f"[`{filename}:{node.start_line}`]({link})"
        else:
            file_cell = f"`{filename}:{node.start_line}`"
        rows.append(f"| `{node.name}` | {node.type.value} | {file_cell} |")
    return "\n".join(rows)


def inject_graph(
    db: str | None = None,
    fqn: str = "cgis.pipeline.IngestionPipeline.run",
    depth: int = 2,
    path_prefix: str = "",
) -> None:
    if not _README.exists():
        msg = f"README not found at {_README}"
        raise FileNotFoundError(msg)
    if not _DIAGRAM.exists():
        msg = (
            f"Diagram not found at {_DIAGRAM}. "
            f"Run: cgis trace ... -f mermaid --internal-only > {_DIAGRAM}"
        )
        raise FileNotFoundError(msg)

    mermaid = _DIAGRAM.read_text(encoding="utf-8").strip()

    parts: list[str] = [
        _SELF_DOC_NOTE,
        "\n```mermaid\n",
        mermaid,
        "\n```\n",
    ]

    if db:
        repo_url = _repo_url()
        table = _node_table(db, fqn, depth, repo_url, path_prefix)
        parts.extend(["\n", table, "\n"])

    block = f"{_START}\n{''.join(parts)}{_END}"

    content = _README.read_text(encoding="utf-8")
    if _START not in content or _END not in content:
        msg = f"Anchor tags not found in {_README}. Add {_START!r} and {_END!r}."
        raise ValueError(msg)

    head, rest = content.split(_START, 1)
    _, tail = rest.split(_END, 1)
    _README.write_text("".join([head, block, tail]), encoding="utf-8")  # NOSONAR
    print(f"✅ Injected architecture graph into {_README}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", default=None, help="SQLite DB for node table")
    parser.add_argument(
        "--fqn",
        default="cgis.pipeline.IngestionPipeline.run",
        help="FQN to trace from",
    )
    parser.add_argument("--depth", type=int, default=2, help="Trace depth")
    parser.add_argument(
        "--path-prefix", default="", help="Prefix prepended to file paths in GitHub links (e.g. 'src/')"
    )
    args = parser.parse_args()
    inject_graph(db=args.db, fqn=args.fqn, depth=args.depth, path_prefix=args.path_prefix)
