"""Unit tests for generated-source detection (#432)."""

from cgis.core.generated import is_generated_source

_BETTERPROTO = """\
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/entities/vehicle.proto
# plugin: python-betterproto2
# This file has been @generated

class Vehicle:
    pass
"""


def test_protobuf_header_is_generated() -> None:
    """The betterproto header — the case that motivated this — is recognised."""
    assert is_generated_source(_BETTERPROTO)


def test_at_generated_alone_is_enough() -> None:
    """`@generated` is the portable convention and needs no companion marker."""
    assert is_generated_source('"""Vehicle DTOs.\n\n@generated\n"""\n')


def test_marker_below_the_header_is_prose_not_a_claim() -> None:
    """A file that *mentions* generation further down is hand-written.

    A comment deep in a module is commentary, not a claim about the file. Stated
    on its own rather than on the owner-api file this once cited: that file turned
    out to carry no "do not edit" anywhere, so it was never at risk and never
    justified the window it was used to justify (#441).
    """
    body = "\n".join(
        [
            '"""Response models for the reservation chat."""',
            "",
            *["# filler"] * 20,
            "# the id is generated by the DB, DO NOT EDIT it by hand",
            "",
            "class Thing:",
            "    pass",
        ]
    )
    assert not is_generated_source(body)


def test_ordinary_source_is_not_generated() -> None:
    """A plain module is not generated."""
    assert not is_generated_source('"""A service."""\n\n\nclass Service:\n    pass\n')


def test_do_not_edit_is_case_insensitive() -> None:
    """Generators disagree on casing — protoc shouts, openapi-generator does not."""
    claim = "# NOTE: This class is auto generated by OpenAPI Generator.\n"
    assert is_generated_source(claim + "# Do not edit the class manually.\n")
    assert is_generated_source(claim + "# DO NOT EDIT!\n")


def test_empty_source_is_not_generated() -> None:
    """An empty file has no marker and must not be swallowed."""
    assert not is_generated_source("")


def test_at_generated_is_matched_case_sensitively() -> None:
    """`@generated` is a machine token; the lowercase spelling is the convention.

    Deliberate and narrow: matching any casing would make a header that merely
    writes "@Generated" in prose a marker. Java's `@Generated` annotation is a
    real spelling, but it is an annotation on a declaration rather than a header
    line, and no Java extractor exists yet — when one lands it can add the
    spelling with a test of its own rather than inherit it by accident.
    """
    assert not is_generated_source("# @GENERATED by something\n")
    assert is_generated_source("# @generated by something\n")


def test_do_not_edit_alone_is_prose_not_a_marker() -> None:
    """ "do not edit" is ordinary English; it needs a generation claim beside it (#441 review).

    A hand-written module whose docstring happens to say it within the header
    would otherwise vanish from the orphan report — silent under-reporting, the
    direction that module explicitly errs away from. Every one of owner-api's six
    genuinely generated headers also says "generated"; this prose does not.
    """
    assert not is_generated_source('"""Docs.\n\nWe do not edit these by hand.\n"""\n')


def test_do_not_edit_beside_a_generation_claim_is_a_marker() -> None:
    """protoc puts the instruction after the claim on one line; openapi splits them."""
    assert is_generated_source("# Generated by the protocol buffer compiler.  DO NOT EDIT!\n")
    assert is_generated_source(
        '"""API.\n\nNOTE: This class is auto generated.\nDo not edit the class manually.\n"""\n'
    )


def test_at_generated_needs_no_companion() -> None:
    """`@generated` is a machine token nobody writes in prose, so it stands alone."""
    assert is_generated_source("# @generated\n")


def test_a_long_header_line_does_not_hide_a_later_marker() -> None:
    """The scanned prefix is capped, so the cap must clear real headers with room.

    betterproto's `# sources:` line is the long one — 690 bytes for owner-api's
    whole five-line window, against a 4096-byte cap. This pins that a header of
    that shape still finds a marker on a later line, so shrinking the cap breaks
    a test rather than silently unclassifying generated files.
    """
    sources = "# sources: " + ", ".join(f"proto/entities/thing_{i}.proto" for i in range(60))
    assert len(sources) > 690
    assert is_generated_source(f"# Protocol buffer compiler.\n{sources}\n# @generated\n")


def test_a_marker_past_the_scanned_prefix_is_not_read() -> None:
    """The cap is a real boundary, not decoration — a marker beyond it is not seen."""
    filler = "# " + "x" * 5000
    assert not is_generated_source(f"{filler}\n# @generated\n")


# Verbatim output shapes, not hand-compressed ones. The earlier openapi tests fed
# a two-line header nobody emits, so they asserted support rather than measuring
# it and could not catch that real output was being missed (#441).
_OPENAPI = '''\
# coding: utf-8

"""
    Pet Store API

    This is a sample server.

    The version of the OpenAPI document: 1.0.0
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

class Pet:
    pass
'''

_GENERATOR_PROJECT = '''\
"""Template for the generated client.

DO NOT EDIT the output; edit this file instead.
"""


class Template:
    pass
'''


def test_real_openapi_generator_output_is_recognised() -> None:
    """openapi-generator puts its markers inside the module docstring, ~line 10.

    The five-line window missed them entirely, so a repository containing an
    openapi client would fill the orphan report with its model classes — the
    exact noise this filter exists to remove — while reporting zero excluded,
    which the docs say means "re-ingest".
    """
    assert is_generated_source(_OPENAPI)


def test_a_code_generation_project_is_not_its_own_output() -> None:
    """ "generated" as a description is not a self-declaration (#441).

    A template file in a code-generation project talks about generated output and
    tells you not to edit the wrong thing. Matching the bare stem `generat` beside
    "do not edit" classified it as generated and silently removed every class in
    it from the report.
    """
    assert not is_generated_source(_GENERATOR_PROJECT)
