"""Unit tests for generated-source detection (#432)."""

from cgis.core.generated import is_generated_source

_BETTERPROTO = """\
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/entities/vehicle.proto
# plugin: python-betterproto2
# This file has been @generated

class Vehicle:
    pass
"""


def test_protobuf_header_is_generated() -> None:
    """The betterproto header — the case that motivated this — is recognised."""
    assert is_generated_source(_BETTERPROTO)


def test_at_generated_alone_is_enough() -> None:
    """`@generated` is the portable convention and needs no companion marker."""
    assert is_generated_source('"""Vehicle DTOs.\n\n@generated\n"""\n')


def test_marker_below_the_header_is_prose_not_a_claim() -> None:
    """A file that *mentions* generation further down is hand-written.

    `owner-api`'s `domains/chat/schemas.py` explains in its module docstring
    that a value is generated on read. Scanning the whole file would classify it
    as generated and hide its classes from the orphan report.
    """
    body = "\n".join(
        [
            '"""Response models for the reservation chat."""',
            "",
            *["# filler"] * 20,
            "# the id is generated by the DB, DO NOT EDIT it by hand",
            "",
            "class Thing:",
            "    pass",
        ]
    )
    assert not is_generated_source(body)


def test_ordinary_source_is_not_generated() -> None:
    """A plain module is not generated."""
    assert not is_generated_source('"""A service."""\n\n\nclass Service:\n    pass\n')


def test_do_not_edit_is_case_insensitive() -> None:
    """Generators disagree on casing — `Do not edit the class manually` is openapi's."""
    assert is_generated_source("# NOTE: Do not edit the class manually.\n")


def test_empty_source_is_not_generated() -> None:
    """An empty file has no marker and must not be swallowed."""
    assert not is_generated_source("")
